2025-07-22 17:20:41,995 - INFO - api_server.py - 19 - api_server: Application startup...
2025-07-22 17:21:48,054 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-22 17:21:48,567 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_tools "HTTP/1.1 200 OK"
2025-07-22 17:21:53,468 - INFO - app.py - 19 - app: Intent determined: {'intent': 'view_character', 'tasks': {'task_1': {'agent': 'character', 'tool': {'name': 'check_for_active_character', 'fields': {'user_id': '123e4567-e89b-12d3-a456-426614174000', 'server_id': '123e4567-e89b-12d3-a456-426614174111'}}}, 'task_2': {'agent': 'character', 'tool': {'name': 'get_current_character', 'fields': {'user_id': '123e4567-e89b-12d3-a456-426614174000', 'server_id': '123e4567-e89b-12d3-a456-426614174111'}}}}}
2025-07-22 17:26:26,240 - INFO - api_server.py - 19 - api_server: Application startup...
2025-07-22 17:26:29,213 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-22 17:26:29,731 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_tools "HTTP/1.1 200 OK"
2025-07-22 17:26:35,407 - INFO - app.py - 19 - app: Intent determined: view_character
2025-07-22 17:26:35,408 - INFO - app.py - 20 - app: Tasks determined: {'task_1': {'agent': 'character', 'tool': {'name': 'check_for_active_character', 'fields': {'user_id': '123e4567-e89b-12d3-a456-426614174000', 'server_id': '123e4567-e89b-12d3-a456-426614174111'}}}, 'task_2': {'agent': 'character', 'tool': {'name': 'get_current_character', 'fields': {'user_id': '123e4567-e89b-12d3-a456-426614174000', 'server_id': '123e4567-e89b-12d3-a456-426614174111'}}}}
2025-07-22 17:33:17,507 - INFO - _client.py - 1740 - _client: HTTP Request: POST http://localhost:8001/orchestrator "HTTP/1.1 200 OK"
2025-07-22 17:33:17,509 - ERROR - app.py - 26 - app: Error in MCP workflow: No active character found for this user on this server.
2025-07-22 17:33:41,577 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-22 17:33:42,083 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_tools "HTTP/1.1 200 OK"
2025-07-22 17:34:12,775 - INFO - api_server.py - 19 - api_server: Application startup...
2025-07-22 17:34:14,585 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-22 17:34:15,077 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_tools "HTTP/1.1 200 OK"
2025-07-22 17:34:21,519 - INFO - app.py - 19 - app: Intent determined: view_character
2025-07-22 17:34:21,520 - INFO - app.py - 20 - app: Tasks determined: {'task_1': {'agent': 'character', 'tool': {'name': 'check_for_active_character', 'fields': {'user_id': '123e4567-e89b-12d3-a456-426614174000', 'server_id': '123e4567-e89b-12d3-a456-426614174111'}}}, 'task_2': {'agent': 'character', 'tool': {'name': 'get_current_character', 'fields': {'user_id': '123e4567-e89b-12d3-a456-426614174000', 'server_id': '123e4567-e89b-12d3-a456-426614174111'}}}}
2025-07-24 17:05:30,550 - INFO - api_server.py - 19 - api_server: Application startup...
2025-07-24 17:05:44,617 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-24 17:05:45,221 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_tools "HTTP/1.1 200 OK"
2025-07-24 17:09:07,317 - INFO - app.py - 19 - app: Intent determined: view_other_player_stats
2025-07-24 17:09:07,318 - INFO - app.py - 20 - app: Tasks determined: {'task_1': {'agent': 'character', 'tool': {'name': 'get_another_players_character', 'fields': {'user_id': '123e4567-e89b-12d3-a456-426614174000', 'server_id': '123e4567-e89b-12d3-a456-426614174111', 'characters_name': 'Kirito'}}}}
2025-07-24 17:09:24,623 - INFO - api_server.py - 19 - api_server: Application startup...
2025-07-24 17:09:40,927 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-24 17:09:41,418 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_tools "HTTP/1.1 200 OK"
2025-07-24 22:21:08,600 - INFO - api_server.py - 19 - api_server: Application startup...
2025-07-24 22:25:30,266 - INFO - api_server.py - 24 - api_server: Application shutdown...
2025-07-24 22:25:40,076 - INFO - api_server.py - 19 - api_server: Application startup...
2025-07-24 22:27:16,074 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-24 22:27:16,669 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents "HTTP/1.1 500 Internal Server Error"
2025-07-24 22:27:16,672 - ERROR - app.py - 35 - app: Error occurred while getting MCP tools: Server error '500 Internal Server Error' for url 'http://localhost:8001/MCPServer/available_intents'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500
2025-07-24 22:28:12,667 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-24 22:28:13,115 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents "HTTP/1.1 200 OK"
2025-07-24 22:28:13,116 - ERROR - app.py - 35 - app: Error occurred while getting MCP tools: 'function' object has no attribute 'get'
2025-07-24 22:28:31,476 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-24 22:28:31,904 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents "HTTP/1.1 200 OK"
2025-07-24 22:29:19,526 - ERROR - app.py - 35 - app: Error occurred while getting MCP tools: 'function' object has no attribute 'get'
2025-07-24 22:29:39,773 - INFO - api_server.py - 24 - api_server: Application shutdown...
2025-07-24 22:29:49,559 - INFO - api_server.py - 19 - api_server: Application startup...
2025-07-24 22:29:50,768 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-24 22:29:51,254 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents "HTTP/1.1 200 OK"
2025-07-24 22:29:51,680 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_tools "HTTP/1.1 200 OK"
2025-07-24 22:29:54,514 - INFO - app.py - 21 - app: Intent determined: None
2025-07-24 22:29:54,514 - INFO - app.py - 22 - app: Tasks determined: None
2025-07-24 22:30:07,378 - INFO - _client.py - 1740 - _client: HTTP Request: POST http://localhost:8001/orchestrator "HTTP/1.1 500 Internal Server Error"
2025-07-24 22:30:07,380 - ERROR - app.py - 35 - app: Error occurred while getting MCP tools: Server error '500 Internal Server Error' for url 'http://localhost:8001/orchestrator'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500
2025-07-24 22:30:07,431 - INFO - api_server.py - 24 - api_server: Application shutdown...
2025-07-24 22:30:19,170 - INFO - api_server.py - 19 - api_server: Application startup...
2025-07-24 22:30:19,176 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-24 22:30:19,661 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents "HTTP/1.1 200 OK"
2025-07-24 22:30:22,278 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_tools "HTTP/1.1 200 OK"
2025-07-24 22:30:24,233 - INFO - app.py - 21 - app: Intent determined: None
2025-07-24 22:30:24,234 - INFO - app.py - 22 - app: Tasks determined: None
2025-07-24 22:30:42,147 - INFO - _client.py - 1740 - _client: HTTP Request: POST http://localhost:8001/orchestrator "HTTP/1.1 500 Internal Server Error"
2025-07-24 22:30:42,149 - ERROR - app.py - 35 - app: Error occurred while getting MCP tools: Server error '500 Internal Server Error' for url 'http://localhost:8001/orchestrator'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500
2025-07-24 22:30:43,756 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-24 22:30:44,178 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents "HTTP/1.1 200 OK"
2025-07-24 22:31:50,517 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_tools "HTTP/1.1 200 OK"
2025-07-24 22:32:08,811 - INFO - api_server.py - 19 - api_server: Application startup...
2025-07-24 22:32:17,347 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-24 22:32:17,931 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents "HTTP/1.1 200 OK"
2025-07-24 22:32:20,285 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_tools "HTTP/1.1 200 OK"
2025-07-24 22:32:21,973 - INFO - app.py - 21 - app: Intent determined: None
2025-07-24 22:32:21,973 - INFO - app.py - 22 - app: Tasks determined: None
2025-07-24 22:32:31,025 - INFO - _client.py - 1740 - _client: HTTP Request: POST http://localhost:8001/orchestrator "HTTP/1.1 500 Internal Server Error"
2025-07-24 22:32:31,027 - ERROR - app.py - 35 - app: Error occurred while getting MCP tools: Server error '500 Internal Server Error' for url 'http://localhost:8001/orchestrator'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500
2025-07-24 22:32:33,733 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-24 22:32:34,158 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents "HTTP/1.1 200 OK"
2025-07-24 22:34:03,366 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_tools "HTTP/1.1 200 OK"
2025-07-24 22:34:24,113 - INFO - api_server.py - 19 - api_server: Application startup...
2025-07-24 22:34:25,506 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-24 22:34:25,996 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents "HTTP/1.1 200 OK"
2025-07-24 22:37:21,412 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_tools "HTTP/1.1 200 OK"
2025-07-24 22:37:25,464 - INFO - app.py - 21 - app: Intent determined: get_another_players_character
2025-07-24 22:37:25,465 - INFO - app.py - 22 - app: Tasks determined: None
2025-07-24 22:42:03,808 - INFO - api_server.py - 19 - api_server: Application startup...
2025-07-24 22:42:04,985 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-24 22:42:05,482 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents "HTTP/1.1 200 OK"
2025-07-24 22:42:44,851 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_tools "HTTP/1.1 200 OK"
2025-07-24 22:42:47,137 - INFO - app.py - 21 - app: Intent determined: get_another_players_character
2025-07-24 22:42:47,137 - INFO - app.py - 22 - app: Tasks determined: None
2025-07-24 22:42:49,269 - INFO - _client.py - 1740 - _client: HTTP Request: POST http://localhost:8001/orchestrator "HTTP/1.1 500 Internal Server Error"
2025-07-24 22:42:49,270 - ERROR - app.py - 35 - app: Error occurred while getting MCP tools: Server error '500 Internal Server Error' for url 'http://localhost:8001/orchestrator'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500
2025-07-24 22:42:49,344 - INFO - api_server.py - 24 - api_server: Application shutdown...
2025-07-24 22:43:00,893 - INFO - api_server.py - 19 - api_server: Application startup...
2025-07-24 22:43:00,898 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-24 22:43:01,380 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents "HTTP/1.1 200 OK"
2025-07-24 23:33:32,803 - INFO - api_server.py - 19 - api_server: Application startup...
2025-07-24 23:33:35,131 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-24 23:33:35,658 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents "HTTP/1.1 200 OK"
2025-07-24 23:35:50,175 - ERROR - llm_service.py - 86 - llm_service: An unexpected error occurred in handle_LLM_intent: _prepare_intent_prompt() takes from 2 to 4 positional arguments but 5 were given
2025-07-24 23:35:50,623 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_tools "HTTP/1.1 200 OK"
2025-07-24 23:35:50,628 - ERROR - app.py - 35 - app: Error occurred while getting MCP tools: 'error'
2025-07-24 23:35:50,692 - INFO - api_server.py - 24 - api_server: Application shutdown...
2025-07-24 23:36:06,922 - INFO - api_server.py - 19 - api_server: Application startup...
2025-07-24 23:36:08,111 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-24 23:36:08,613 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents "HTTP/1.1 200 OK"
2025-07-24 23:37:06,633 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_tools "HTTP/1.1 200 OK"
2025-07-24 23:37:06,636 - ERROR - app.py - 35 - app: Error occurred while getting MCP tools: 'error'
2025-07-24 23:37:29,961 - INFO - api_server.py - 24 - api_server: Application shutdown...
2025-07-24 23:37:42,253 - INFO - api_server.py - 19 - api_server: Application startup...
2025-07-24 23:37:57,548 - INFO - api_server.py - 24 - api_server: Application shutdown...
2025-07-24 23:38:07,474 - INFO - api_server.py - 19 - api_server: Application startup...
2025-07-24 23:38:09,206 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-24 23:38:09,714 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents "HTTP/1.1 200 OK"
2025-07-24 23:38:14,031 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_tools "HTTP/1.1 200 OK"
2025-07-24 23:38:14,033 - ERROR - llm_service.py - 27 - llm_service: No user query provided in the request.
2025-07-24 23:38:14,034 - INFO - app.py - 21 - app: Intent determined: None
2025-07-24 23:38:14,034 - INFO - app.py - 22 - app: Tasks determined: None
2025-07-24 23:38:14,468 - INFO - _client.py - 1740 - _client: HTTP Request: POST http://localhost:8001/orchestrator "HTTP/1.1 500 Internal Server Error"
2025-07-24 23:38:14,469 - ERROR - app.py - 35 - app: Error occurred while getting MCP tools: Server error '500 Internal Server Error' for url 'http://localhost:8001/orchestrator'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500
2025-07-25 12:46:52,303 - INFO - api_server.py - 19 - api_server: Application startup...
2025-07-25 12:47:24,311 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-25 12:47:24,905 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents "HTTP/1.1 200 OK"
2025-07-25 12:48:22,129 - INFO - api_server.py - 19 - api_server: Application startup...
2025-07-25 12:49:01,030 - INFO - api_server.py - 24 - api_server: Application shutdown...
2025-07-25 12:49:10,505 - INFO - api_server.py - 19 - api_server: Application startup...
2025-07-25 12:50:27,268 - INFO - api_server.py - 24 - api_server: Application shutdown...
2025-07-25 12:50:37,001 - INFO - api_server.py - 19 - api_server: Application startup...
2025-07-25 12:50:38,668 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-25 12:50:39,172 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents "HTTP/1.1 200 OK"
2025-07-25 12:50:58,555 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-25 12:50:59,073 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents "HTTP/1.1 200 OK"
2025-07-25 12:51:40,729 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-25 12:51:41,157 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents "HTTP/1.1 200 OK"
2025-07-25 12:52:15,042 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-25 12:52:19,124 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents "HTTP/1.1 200 OK"
2025-07-25 12:52:34,925 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-25 12:52:37,569 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents "HTTP/1.1 200 OK"
2025-07-25 13:00:37,847 - WARNING - before_sleep.py - 65 - before_sleep: Retrying langchain_google_genai.llms._completion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised RetryError: Timeout of 600.0s exceeded, last exception: 503 failed to connect to all addresses; last error: UNKNOWN: ipv4:192.178.162.95:443: tcp handshaker shutdown.
2025-07-25 13:00:55,198 - WARNING - before_sleep.py - 65 - before_sleep: Retrying langchain_google_genai.llms._completion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised RetryError: Timeout of 600.0s exceeded, last exception: 503 failed to connect to all addresses; last error: UNKNOWN: ipv4:192.178.152.95:443: tcp handshaker shutdown.
2025-07-25 13:01:36,281 - WARNING - before_sleep.py - 65 - before_sleep: Retrying langchain_google_genai.llms._completion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised RetryError: Timeout of 600.0s exceeded, last exception: 503 failed to connect to all addresses; last error: UNKNOWN: ipv4:192.178.152.95:443: tcp handshaker shutdown.
2025-07-25 13:01:38,261 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-25 13:01:42,536 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents "HTTP/1.1 200 OK"
2025-07-25 13:02:19,070 - WARNING - before_sleep.py - 65 - before_sleep: Retrying langchain_google_genai.llms._completion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised RetryError: Timeout of 600.0s exceeded, last exception: 503 failed to connect to all addresses; last error: UNAVAILABLE: ipv4:172.253.113.95:443: ConnectEx: Connection timed out (A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
 -- 10060).
2025-07-25 13:02:59,054 - WARNING - before_sleep.py - 65 - before_sleep: Retrying langchain_google_genai.llms._completion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised RetryError: Timeout of 600.0s exceeded, last exception: 503 failed to connect to all addresses; last error: UNAVAILABLE: ipv4:192.178.152.95:443: ConnectEx: Connection timed out (A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
 -- 10060).
2025-07-25 13:08:56,331 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-25 13:08:56,771 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents "HTTP/1.1 200 OK"
2025-07-25 13:09:01,404 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_tools "HTTP/1.1 200 OK"
2025-07-25 13:09:01,407 - ERROR - llm_service.py - 27 - llm_service: No user query provided in the request.
2025-07-25 13:09:01,408 - INFO - app.py - 21 - app: Intent determined: None
2025-07-25 13:09:01,408 - INFO - app.py - 22 - app: Tasks determined: None
2025-07-25 13:09:23,857 - INFO - _client.py - 1740 - _client: HTTP Request: POST http://localhost:8001/orchestrator "HTTP/1.1 500 Internal Server Error"
2025-07-25 13:09:23,859 - ERROR - app.py - 35 - app: Error occurred while getting MCP tools: Server error '500 Internal Server Error' for url 'http://localhost:8001/orchestrator'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500
2025-07-25 13:09:24,432 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_tools "HTTP/1.1 200 OK"
2025-07-25 13:09:24,435 - ERROR - llm_service.py - 27 - llm_service: No user query provided in the request.
2025-07-25 13:09:24,603 - INFO - app.py - 21 - app: Intent determined: None
2025-07-25 13:09:24,603 - INFO - app.py - 22 - app: Tasks determined: None
2025-07-25 13:09:24,774 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_tools "HTTP/1.1 200 OK"
2025-07-25 13:09:24,777 - ERROR - llm_service.py - 27 - llm_service: No user query provided in the request.
2025-07-25 13:09:24,778 - INFO - app.py - 21 - app: Intent determined: None
2025-07-25 13:09:24,778 - INFO - app.py - 22 - app: Tasks determined: None
2025-07-25 13:09:24,948 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_tools "HTTP/1.1 200 OK"
2025-07-25 13:09:24,949 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_tools "HTTP/1.1 200 OK"
2025-07-25 13:09:24,951 - ERROR - llm_service.py - 27 - llm_service: No user query provided in the request.
2025-07-25 13:09:24,951 - ERROR - llm_service.py - 27 - llm_service: No user query provided in the request.
2025-07-25 13:09:24,952 - INFO - app.py - 21 - app: Intent determined: None
2025-07-25 13:09:24,952 - INFO - app.py - 22 - app: Tasks determined: None
2025-07-25 13:09:25,119 - INFO - app.py - 21 - app: Intent determined: None
2025-07-25 13:09:25,119 - INFO - app.py - 22 - app: Tasks determined: None
2025-07-25 13:09:25,290 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_tools "HTTP/1.1 200 OK"
2025-07-25 13:09:25,291 - INFO - _client.py - 1740 - _client: HTTP Request: POST http://localhost:8001/orchestrator "HTTP/1.1 500 Internal Server Error"
2025-07-25 13:09:25,292 - ERROR - app.py - 35 - app: Error occurred while getting MCP tools: Server error '500 Internal Server Error' for url 'http://localhost:8001/orchestrator'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500
2025-07-25 13:09:25,292 - ERROR - llm_service.py - 27 - llm_service: No user query provided in the request.
2025-07-25 13:09:25,293 - INFO - app.py - 21 - app: Intent determined: None
2025-07-25 13:09:25,293 - INFO - app.py - 22 - app: Tasks determined: None
2025-07-25 13:09:25,461 - INFO - _client.py - 1740 - _client: HTTP Request: POST http://localhost:8001/orchestrator "HTTP/1.1 500 Internal Server Error"
2025-07-25 13:09:25,462 - ERROR - app.py - 35 - app: Error occurred while getting MCP tools: Server error '500 Internal Server Error' for url 'http://localhost:8001/orchestrator'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500
2025-07-25 13:09:25,551 - INFO - _client.py - 1740 - _client: HTTP Request: POST http://localhost:8001/orchestrator "HTTP/1.1 500 Internal Server Error"
2025-07-25 13:09:25,552 - ERROR - app.py - 35 - app: Error occurred while getting MCP tools: Server error '500 Internal Server Error' for url 'http://localhost:8001/orchestrator'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500
2025-07-25 13:09:25,555 - INFO - _client.py - 1740 - _client: HTTP Request: POST http://localhost:8001/orchestrator "HTTP/1.1 500 Internal Server Error"
2025-07-25 13:09:25,556 - ERROR - app.py - 35 - app: Error occurred while getting MCP tools: Server error '500 Internal Server Error' for url 'http://localhost:8001/orchestrator'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500
2025-07-25 13:09:25,721 - INFO - _client.py - 1740 - _client: HTTP Request: POST http://localhost:8001/orchestrator "HTTP/1.1 500 Internal Server Error"
2025-07-25 13:09:25,721 - ERROR - app.py - 35 - app: Error occurred while getting MCP tools: Server error '500 Internal Server Error' for url 'http://localhost:8001/orchestrator'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500
2025-07-25 13:09:46,412 - INFO - api_server.py - 19 - api_server: Application startup...
2025-07-25 13:09:49,174 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-25 13:09:49,668 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents "HTTP/1.1 200 OK"
2025-07-25 13:10:08,472 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_tools "HTTP/1.1 200 OK"
2025-07-25 13:10:08,476 - ERROR - llm_service.py - 27 - llm_service: No user query provided in the request.
2025-07-25 13:10:08,477 - INFO - app.py - 21 - app: Intent determined: None
2025-07-25 13:10:08,477 - INFO - app.py - 22 - app: Tasks determined: None
2025-07-25 13:10:27,602 - INFO - _client.py - 1740 - _client: HTTP Request: POST http://localhost:8001/orchestrator "HTTP/1.1 500 Internal Server Error"
2025-07-25 13:10:27,604 - ERROR - app.py - 35 - app: Error occurred while getting MCP tools: Server error '500 Internal Server Error' for url 'http://localhost:8001/orchestrator'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500
2025-07-25 13:10:31,303 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-25 13:10:31,730 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents "HTTP/1.1 200 OK"
2025-07-25 13:10:35,757 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_tools "HTTP/1.1 200 OK"
2025-07-25 13:10:38,353 - ERROR - llm_service.py - 27 - llm_service: No user query provided in the request.
2025-07-25 13:11:03,745 - INFO - app.py - 21 - app: Intent determined: None
2025-07-25 13:11:03,746 - INFO - app.py - 22 - app: Tasks determined: None
2025-07-25 13:11:08,728 - INFO - _client.py - 1740 - _client: HTTP Request: POST http://localhost:8001/orchestrator "HTTP/1.1 500 Internal Server Error"
2025-07-25 13:11:08,729 - ERROR - app.py - 35 - app: Error occurred while getting MCP tools: Server error '500 Internal Server Error' for url 'http://localhost:8001/orchestrator'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500
2025-07-25 13:11:10,258 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-25 13:11:10,699 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents "HTTP/1.1 200 OK"
2025-07-25 13:11:20,623 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_tools "HTTP/1.1 200 OK"
2025-07-25 13:12:42,994 - ERROR - llm_service.py - 27 - llm_service: No user query provided in the request.
2025-07-25 13:12:43,120 - INFO - app.py - 21 - app: Intent determined: None
2025-07-25 13:12:43,121 - INFO - app.py - 22 - app: Tasks determined: None
2025-07-25 13:12:43,559 - INFO - _client.py - 1740 - _client: HTTP Request: POST http://localhost:8001/orchestrator "HTTP/1.1 500 Internal Server Error"
2025-07-25 13:12:43,560 - ERROR - app.py - 35 - app: Error occurred while getting MCP tools: Server error '500 Internal Server Error' for url 'http://localhost:8001/orchestrator'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500
2025-07-25 13:12:43,619 - INFO - api_server.py - 24 - api_server: Application shutdown...
2025-07-25 13:12:55,526 - INFO - api_server.py - 19 - api_server: Application startup...
2025-07-25 13:12:57,713 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-25 13:12:58,233 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents "HTTP/1.1 200 OK"
2025-07-25 13:13:01,910 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_tools "HTTP/1.1 200 OK"
2025-07-25 13:29:41,359 - ERROR - llm_service.py - 85 - llm_service: An unexpected error occurred in handle_LLM_intent: replace() argument 2 must be str, not dict
2025-07-25 13:29:41,362 - INFO - app.py - 21 - app: Intent determined: None
2025-07-25 13:29:41,362 - INFO - app.py - 22 - app: Tasks determined: None
2025-07-25 15:11:08,016 - INFO - _client.py - 1740 - _client: HTTP Request: POST http://localhost:8001/orchestrator "HTTP/1.1 500 Internal Server Error"
2025-07-25 15:11:08,018 - ERROR - app.py - 35 - app: Error occurred while getting MCP tools: Server error '500 Internal Server Error' for url 'http://localhost:8001/orchestrator'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500
2025-07-25 15:15:45,622 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-25 15:15:46,064 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents "HTTP/1.1 200 OK"
2025-07-25 15:15:49,737 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_tools "HTTP/1.1 200 OK"
2025-07-25 15:16:06,393 - ERROR - llm_service.py - 85 - llm_service: An unexpected error occurred in handle_LLM_intent: replace() argument 2 must be str, not dict
2025-07-25 15:16:06,395 - INFO - app.py - 21 - app: Intent determined: None
2025-07-25 15:16:06,396 - INFO - app.py - 22 - app: Tasks determined: None
2025-07-25 15:16:07,378 - INFO - _client.py - 1740 - _client: HTTP Request: POST http://localhost:8001/orchestrator "HTTP/1.1 500 Internal Server Error"
2025-07-25 15:16:26,035 - ERROR - app.py - 35 - app: Error occurred while getting MCP tools: Server error '500 Internal Server Error' for url 'http://localhost:8001/orchestrator'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500
2025-07-25 15:16:28,995 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-25 15:16:29,440 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents "HTTP/1.1 200 OK"
2025-07-25 15:16:35,136 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_tools "HTTP/1.1 200 OK"
2025-07-25 15:19:47,247 - ERROR - llm_service.py - 85 - llm_service: An unexpected error occurred in handle_LLM_intent: replace() argument 2 must be str, not dict
2025-07-25 15:19:47,251 - INFO - app.py - 21 - app: Intent determined: None
2025-07-25 15:19:47,251 - INFO - app.py - 22 - app: Tasks determined: None
2025-07-25 15:19:49,396 - INFO - _client.py - 1740 - _client: HTTP Request: POST http://localhost:8001/orchestrator "HTTP/1.1 500 Internal Server Error"
2025-07-25 15:19:49,398 - ERROR - app.py - 35 - app: Error occurred while getting MCP tools: Server error '500 Internal Server Error' for url 'http://localhost:8001/orchestrator'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500
2025-07-25 15:19:49,455 - INFO - api_server.py - 24 - api_server: Application shutdown...
2025-07-25 15:20:02,147 - INFO - api_server.py - 19 - api_server: Application startup...
2025-07-25 15:20:02,153 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-25 15:20:02,650 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents "HTTP/1.1 200 OK"
2025-07-25 15:20:42,787 - ERROR - llm_service.py - 94 - llm_service: An unexpected error occurred in handle_LLM_intent: replace() argument 2 must be str, not coroutine
2025-07-25 15:20:43,231 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_tools "HTTP/1.1 200 OK"
2025-07-25 15:20:43,877 - ERROR - llm_service.py - 94 - llm_service: An unexpected error occurred in handle_LLM_intent: replace() argument 2 must be str, not coroutine
2025-07-25 15:20:43,878 - INFO - app.py - 21 - app: Intent determined: None
2025-07-25 15:20:43,879 - INFO - app.py - 22 - app: Tasks determined: None
2025-07-25 15:20:45,016 - INFO - _client.py - 1740 - _client: HTTP Request: POST http://localhost:8001/orchestrator "HTTP/1.1 500 Internal Server Error"
2025-07-25 15:20:45,018 - ERROR - app.py - 35 - app: Error occurred while getting MCP tools: Server error '500 Internal Server Error' for url 'http://localhost:8001/orchestrator'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500
2025-07-25 15:20:45,082 - INFO - api_server.py - 24 - api_server: Application shutdown...
2025-07-25 15:20:55,004 - INFO - api_server.py - 19 - api_server: Application startup...
2025-07-25 15:20:57,737 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-25 15:20:58,227 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents "HTTP/1.1 200 OK"
2025-07-25 15:21:10,060 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_tools "HTTP/1.1 200 OK"
2025-07-25 15:24:23,440 - INFO - app.py - 21 - app: Intent determined: create_character
2025-07-25 15:24:23,441 - INFO - app.py - 22 - app: Tasks determined: {'task_1': {'agent': 'agent_1', 'tool': {'name': 'create_character', 'fields': {'first_name': None, 'last_name': None, 'character_name': 'leeroy', 'character_class': 'warrior', 'cursor_color': None, 'height': None, 'physique': None, 'age': None, 'birthday': None, 'bio': None, 'level': None, 'experience': None, 'experience_to_next_level': None, 'equipment': None, 'consumables': None, 'misc': None, 'cratable': None, 'key_items': None, 'currency': None, 'head': None, 'chest': None, 'legs': None, 'arms': None, 'accessory1': None, 'accessory2': None, 'left_hand': None, 'right_hand': None, 'guild': None, 'party': None, 'hp': None, 'str': None, 'def': None, 'spe': None, 'dex': None, 'cha': None, 'points_to_distribute': None, 'status_ailment': None, 'battle_status': None, 'damage': None, 'defense': None, 'current_hp': None, 'user_id': None, 'server_id': None, 'active': None}}}, 'task_2': {'agent': 'agent_2', 'tool': {'name': 'missing_fields', 'fields': {'server_id': None, 'user_id': None, 'missing_fields': ['user_id', 'server_id', 'first_name', 'last_name', 'cursor_color', 'height', 'physique', 'age', 'birthday', 'bio', 'level', 'experience', 'experience_to_next_level', 'equipment', 'consumables', 'misc', 'cratable', 'key_items', 'currency', 'head', 'chest', 'legs', 'arms', 'accessory1', 'accessory2', 'left_hand', 'right_hand', 'guild', 'party', 'hp', 'str', 'def', 'spe', 'dex', 'cha', 'points_to_distribute', 'status_ailment', 'battle_status', 'damage', 'defense', 'current_hp', 'active']}}}}
2025-07-25 15:24:24,877 - INFO - _client.py - 1740 - _client: HTTP Request: POST http://localhost:8001/orchestrator "HTTP/1.1 200 OK"
2025-07-25 15:24:24,879 - ERROR - app.py - 28 - app: Error in MCP workflow: Error importing agent: No module named 'Agents.agent_1'
2025-07-25 15:24:24,924 - INFO - api_server.py - 24 - api_server: Application shutdown...
2025-07-25 15:24:37,227 - INFO - api_server.py - 19 - api_server: Application startup...
2025-07-25 15:24:39,354 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-25 15:24:39,874 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents "HTTP/1.1 200 OK"
2025-07-25 15:24:59,007 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_tools "HTTP/1.1 200 OK"
2025-07-25 15:26:34,254 - INFO - app.py - 21 - app: Intent determined: create_character
2025-07-25 15:26:34,254 - INFO - app.py - 22 - app: Tasks determined: {'task_1': {'agent': 'agent_1', 'tool': {'name': 'create_character', 'fields': {'first_name': None, 'last_name': None, 'characters_name': 'leeroy', 'characters_class': 'warrior', 'cursor_color': None, 'height': None, 'physique': None, 'age': None, 'birthday': None, 'bio': None, 'level': None, 'experience': None, 'experience_to_next_level': None, 'equipment': None, 'consumables': None, 'misc': None, 'cratable': None, 'key_items': None, 'currency': None, 'head': None, 'chest': None, 'legs': None, 'arms': None, 'accessory1': None, 'accessory2': None, 'left_hand': None, 'right_hand': None, 'guild': None, 'party': None, 'hp': None, 'str': None, 'def': None, 'spe': None, 'dex': None, 'cha': None, 'points_to_distribute': None, 'status_ailment': None, 'battle_status': None, 'damage': None, 'defense': None, 'current_hp': None, 'user_id': '123e4567-e89b-12d3-a456-426614174000', 'server_id': '123e4567-e89b-12d3-a456-426614174111', 'active': None}}}, 'task_2': {'agent': 'agent_2', 'tool': {'name': 'create_character', 'fields': {'first_name': None, 'last_name': None, 'characters_name': 'leeroy', 'characters_class': 'warrior', 'cursor_color': None, 'height': None, 'physique': None, 'age': None, 'birthday': None, 'bio': None, 'level': None, 'experience': None, 'experience_to_next_level': None, 'equipment': None, 'consumables': None, 'misc': None, 'cratable': None, 'key_items': None, 'currency': None, 'head': None, 'chest': None, 'legs': None, 'arms': None, 'accessory1': None, 'accessory2': None, 'left_hand': None, 'right_hand': None, 'guild': None, 'party': None, 'hp': None, 'str': None, 'def': None, 'spe': None, 'dex': None, 'cha': None, 'points_to_distribute': None, 'status_ailment': None, 'battle_status': None, 'damage': None, 'defense': None, 'current_hp': None, 'user_id': '123e4567-e89b-12d3-a456-426614174000', 'server_id': '123e4567-e89b-12d3-a456-426614174111', 'active': None}}}}
2025-07-25 15:28:42,844 - INFO - _client.py - 1740 - _client: HTTP Request: POST http://localhost:8001/orchestrator "HTTP/1.1 500 Internal Server Error"
2025-07-25 15:28:42,846 - ERROR - app.py - 35 - app: Error occurred while getting MCP tools: Server error '500 Internal Server Error' for url 'http://localhost:8001/orchestrator'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500
2025-07-25 15:28:42,918 - INFO - api_server.py - 24 - api_server: Application shutdown...
2025-07-25 15:28:54,787 - INFO - api_server.py - 19 - api_server: Application startup...
2025-07-25 15:29:13,227 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-25 15:29:13,717 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents "HTTP/1.1 200 OK"
2025-07-25 15:29:16,094 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_tools "HTTP/1.1 200 OK"
2025-07-25 15:29:54,560 - INFO - app.py - 21 - app: Intent determined: create_character
2025-07-25 15:29:54,561 - INFO - app.py - 22 - app: Tasks determined: {'task_1': {'agent': 'agent_1', 'tool': {'name': 'check_character_limit', 'fields': {'server_id': '123e4567-e89b-12d3-a456-426614174111', 'user_id': '123e4567-e89b-12d3-a456-426614174000'}}}, 'task_2': {'agent': 'agent_1', 'tool': {'name': 'check_for_active_character', 'fields': {'server_id': '123e4567-e89b-12d3-a456-426614174111', 'user_id': '123e4567-e89b-12d3-a456-426614174000'}}}, 'task_3': {'agent': 'agent_2', 'tool': {'name': 'create_character', 'fields': {'first_name': None, 'last_name': None, 'characters_name': 'leeroy', 'characters_class': 'warrior', 'cursor_color': None, 'height': None, 'physique': None, 'age': None, 'birthday': None, 'bio': None, 'level': None, 'experience': None, 'experience_to_next_level': None, 'equipment': None, 'consumables': None, 'misc': None, 'cratable': None, 'key_items': None, 'currency': None, 'head': None, 'chest': None, 'legs': None, 'arms': None, 'accessory1': None, 'accessory2': None, 'left_hand': None, 'right_hand': None, 'guild': None, 'party': None, 'hp': None, 'str': None, 'def': None, 'spe': None, 'dex': None, 'cha': None, 'points_to_distribute': None, 'status_ailment': None, 'battle_status': None, 'damage': None, 'defense': None, 'current_hp': None, 'user_id': '123e4567-e89b-12d3-a456-426614174000', 'server_id': '123e4567-e89b-12d3-a456-426614174111', 'active': None}}}}
2025-07-25 15:29:57,124 - INFO - _client.py - 1740 - _client: HTTP Request: POST http://localhost:8001/orchestrator "HTTP/1.1 200 OK"
2025-07-25 15:29:57,125 - ERROR - app.py - 28 - app: Error in MCP workflow: Error importing agent: No module named 'Agents.agent_1'
2025-07-25 15:30:56,633 - INFO - api_server.py - 19 - api_server: Application startup...
2025-07-25 15:31:34,861 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-25 15:31:35,457 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents "HTTP/1.1 200 OK"
2025-07-25 15:31:37,929 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_tools "HTTP/1.1 200 OK"
2025-07-25 15:32:39,705 - INFO - app.py - 21 - app: Intent determined: create_character
2025-07-25 15:32:39,706 - INFO - app.py - 22 - app: Tasks determined: {'task_1': {'agent': 'agent_1', 'tool': {'name': 'check_character_limit', 'fields': {'server_id': '123e4567-e89b-12d3-a456-426614174111', 'user_id': '123e4567-e89b-12d3-a456-426614174000'}}}, 'task_2': {'agent': 'agent_1', 'tool': {'name': 'check_for_active_character', 'fields': {'server_id': '123e4567-e89b-12d3-a456-426614174111', 'user_id': '123e4567-e89b-12d3-a456-426614174000'}}}, 'task_3': {'agent': 'agent_2', 'tool': {'name': 'create_character', 'fields': {'characters_name': 'leeroy', 'characters_class': 'warrior', 'user_id': '123e4567-e89b-12d3-a456-426614174000', 'server_id': '123e4567-e89b-12d3-a456-426614174111'}}}}
2025-07-25 17:06:32,350 - INFO - _client.py - 1740 - _client: HTTP Request: POST http://localhost:8001/orchestrator "HTTP/1.1 200 OK"
2025-07-25 17:06:32,352 - ERROR - app.py - 28 - app: Error in MCP workflow: Error importing agent: No module named 'Agents.agent_1'
2025-07-25 17:06:32,398 - INFO - api_server.py - 24 - api_server: Application shutdown...
2025-07-25 17:06:44,604 - INFO - api_server.py - 19 - api_server: Application startup...
2025-07-25 17:06:47,885 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-25 17:06:48,475 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents "HTTP/1.1 200 OK"
2025-07-25 17:06:50,363 - ERROR - app.py - 35 - app: Error occurred while getting MCP tools: get_available_tools() missing 1 required positional argument: 'tools'
2025-07-25 17:07:06,851 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-25 17:07:07,305 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents "HTTP/1.1 200 OK"
2025-07-25 17:07:08,762 - ERROR - app.py - 35 - app: Error occurred while getting MCP tools: get_available_tools() missing 1 required positional argument: 'tools'
2025-07-25 17:07:21,588 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-25 17:07:22,091 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents "HTTP/1.1 200 OK"
2025-07-25 17:07:52,873 - ERROR - app.py - 35 - app: Error occurred while getting MCP tools: get_available_tools() missing 1 required positional argument: 'tools'
2025-07-25 17:07:52,983 - INFO - api_server.py - 24 - api_server: Application shutdown...
2025-07-25 17:08:05,332 - INFO - api_server.py - 19 - api_server: Application startup...
2025-07-25 17:08:24,449 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-25 17:08:25,030 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents "HTTP/1.1 200 OK"
2025-07-25 17:08:51,315 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_tools?agents=%7B%27agent_1%27%3A+%27character%27%2C+%27agent_2%27%3A+%27database%27%7D&tools=%7B%27tool_1%27%3A+%27check_character_limit%27%2C+%27tool_2%27%3A+%27check_for_active_character%27%2C+%27tool_3%27%3A+%27create_character%27%7D "HTTP/1.1 422 Unprocessable Content"
2025-07-25 17:08:51,317 - ERROR - app.py - 35 - app: Error occurred while getting MCP tools: Client error '422 Unprocessable Content' for url 'http://localhost:8001/MCPServer/available_tools?agents=%7B%27agent_1%27%3A+%27character%27%2C+%27agent_2%27%3A+%27database%27%7D&tools=%7B%27tool_1%27%3A+%27check_character_limit%27%2C+%27tool_2%27%3A+%27check_for_active_character%27%2C+%27tool_3%27%3A+%27create_character%27%7D'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/422
2025-07-25 17:11:37,959 - INFO - api_server.py - 24 - api_server: Application shutdown...
2025-07-25 17:11:49,866 - INFO - api_server.py - 19 - api_server: Application startup...
2025-07-25 17:11:55,138 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-25 17:11:55,627 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents "HTTP/1.1 200 OK"
2025-07-25 17:11:58,085 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_tools?agents=%7B%27agent_1%27%3A+%27character%27%2C+%27agent_2%27%3A+%27database%27%7D&tools=%7B%27tool_1%27%3A+%27check_character_limit%27%2C+%27tool_2%27%3A+%27check_for_active_character%27%2C+%27tool_3%27%3A+%27create_character%27%7D "HTTP/1.1 422 Unprocessable Content"
2025-07-25 17:11:58,086 - ERROR - app.py - 35 - app: Error occurred while getting MCP tools: Client error '422 Unprocessable Content' for url 'http://localhost:8001/MCPServer/available_tools?agents=%7B%27agent_1%27%3A+%27character%27%2C+%27agent_2%27%3A+%27database%27%7D&tools=%7B%27tool_1%27%3A+%27check_character_limit%27%2C+%27tool_2%27%3A+%27check_for_active_character%27%2C+%27tool_3%27%3A+%27create_character%27%7D'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/422
2025-07-25 17:12:11,839 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-25 17:12:12,279 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents "HTTP/1.1 200 OK"
2025-07-25 17:12:23,728 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_tools?agents=%7B%27agent_1%27%3A+%27character%27%2C+%27agent_2%27%3A+%27database%27%7D&tools=%7B%27tool_1%27%3A+%27check_character_limit%27%2C+%27tool_2%27%3A+%27check_for_active_character%27%2C+%27tool_3%27%3A+%27create_character%27%7D "HTTP/1.1 422 Unprocessable Content"
2025-07-25 17:12:23,730 - ERROR - app.py - 35 - app: Error occurred while getting MCP tools: Client error '422 Unprocessable Content' for url 'http://localhost:8001/MCPServer/available_tools?agents=%7B%27agent_1%27%3A+%27character%27%2C+%27agent_2%27%3A+%27database%27%7D&tools=%7B%27tool_1%27%3A+%27check_character_limit%27%2C+%27tool_2%27%3A+%27check_for_active_character%27%2C+%27tool_3%27%3A+%27create_character%27%7D'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/422
2025-07-25 17:12:32,709 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-25 17:12:33,148 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents "HTTP/1.1 200 OK"
2025-07-25 17:17:16,262 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_tools?agents=%7B%27agent_1%27%3A+%27character%27%2C+%27agent_2%27%3A+%27database%27%7D&tools=%7B%27tool_1%27%3A+%27check_character_limit%27%2C+%27tool_2%27%3A+%27check_for_active_character%27%2C+%27tool_3%27%3A+%27create_character%27%7D "HTTP/1.1 422 Unprocessable Content"
2025-07-25 17:17:18,967 - ERROR - app.py - 35 - app: Error occurred while getting MCP tools: Client error '422 Unprocessable Content' for url 'http://localhost:8001/MCPServer/available_tools?agents=%7B%27agent_1%27%3A+%27character%27%2C+%27agent_2%27%3A+%27database%27%7D&tools=%7B%27tool_1%27%3A+%27check_character_limit%27%2C+%27tool_2%27%3A+%27check_for_active_character%27%2C+%27tool_3%27%3A+%27create_character%27%7D'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/422
2025-07-25 17:17:18,969 - INFO - api_server.py - 24 - api_server: Application shutdown...
2025-07-25 17:17:30,895 - INFO - api_server.py - 19 - api_server: Application startup...
2025-07-25 17:17:32,799 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-25 17:17:33,303 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents "HTTP/1.1 200 OK"
2025-07-25 17:17:40,360 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_tools?agents=%7B%22agent_1%22%3A+%22character%22%2C+%22agent_2%22%3A+%22database%22%7D&tools=%7B%22tool_1%22%3A+%22check_character_limit%22%2C+%22tool_2%22%3A+%22check_for_active_character%22%2C+%22tool_3%22%3A+%22create_character%22%7D "HTTP/1.1 422 Unprocessable Content"
2025-07-25 17:17:40,361 - ERROR - app.py - 35 - app: Error occurred while getting MCP tools: Client error '422 Unprocessable Content' for url 'http://localhost:8001/MCPServer/available_tools?agents=%7B%22agent_1%22%3A+%22character%22%2C+%22agent_2%22%3A+%22database%22%7D&tools=%7B%22tool_1%22%3A+%22check_character_limit%22%2C+%22tool_2%22%3A+%22check_for_active_character%22%2C+%22tool_3%22%3A+%22create_character%22%7D'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/422
2025-07-25 17:18:42,008 - INFO - api_server.py - 24 - api_server: Application shutdown...
2025-07-25 17:18:53,793 - INFO - api_server.py - 19 - api_server: Application startup...
2025-07-25 17:18:53,795 - INFO - api_server.py - 24 - api_server: Application shutdown...
2025-07-25 17:19:03,861 - INFO - api_server.py - 19 - api_server: Application startup...
2025-07-25 17:19:09,758 - INFO - api_server.py - 24 - api_server: Application shutdown...
2025-07-25 17:19:19,974 - INFO - api_server.py - 19 - api_server: Application startup...
2025-07-25 17:19:25,571 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-25 17:19:26,073 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents "HTTP/1.1 200 OK"
2025-07-25 17:19:28,326 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_tools?agents=%7B%22agent_1%22%3A+%22character%22%2C+%22agent_2%22%3A+%22database%22%7D&tools=%7B%22tool_1%22%3A+%22check_character_limit%22%2C+%22tool_2%22%3A+%22check_for_active_character%22%2C+%22tool_3%22%3A+%22create_character%22%7D "HTTP/1.1 422 Unprocessable Content"
2025-07-25 17:19:28,328 - ERROR - app.py - 35 - app: Error occurred while getting MCP tools: Client error '422 Unprocessable Content' for url 'http://localhost:8001/MCPServer/available_tools?agents=%7B%22agent_1%22%3A+%22character%22%2C+%22agent_2%22%3A+%22database%22%7D&tools=%7B%22tool_1%22%3A+%22check_character_limit%22%2C+%22tool_2%22%3A+%22check_for_active_character%22%2C+%22tool_3%22%3A+%22create_character%22%7D'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/422
2025-07-25 17:19:49,598 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-25 17:19:50,104 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents "HTTP/1.1 200 OK"
2025-07-25 17:20:31,557 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_tools?agents=%7B%22agent_1%22%3A+%22character%22%2C+%22agent_2%22%3A+%22database%22%7D&tools=%7B%22tool_1%22%3A+%22check_character_limit%22%2C+%22tool_2%22%3A+%22check_for_active_character%22%2C+%22tool_3%22%3A+%22create_character%22%7D "HTTP/1.1 422 Unprocessable Content"
2025-07-25 17:20:31,558 - ERROR - app.py - 35 - app: Error occurred while getting MCP tools: Client error '422 Unprocessable Content' for url 'http://localhost:8001/MCPServer/available_tools?agents=%7B%22agent_1%22%3A+%22character%22%2C+%22agent_2%22%3A+%22database%22%7D&tools=%7B%22tool_1%22%3A+%22check_character_limit%22%2C+%22tool_2%22%3A+%22check_for_active_character%22%2C+%22tool_3%22%3A+%22create_character%22%7D'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/422
2025-07-25 17:21:23,103 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-25 17:21:23,540 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents "HTTP/1.1 200 OK"
2025-07-25 17:21:49,503 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_tools?agents=%7B%22agent_1%22%3A+%22character%22%2C+%22agent_2%22%3A+%22database%22%7D&tools=%7B%22tool_1%22%3A+%22check_character_limit%22%2C+%22tool_2%22%3A+%22check_for_active_character%22%2C+%22tool_3%22%3A+%22create_character%22%7D "HTTP/1.1 422 Unprocessable Content"
2025-07-25 17:21:49,505 - ERROR - app.py - 35 - app: Error occurred while getting MCP tools: Client error '422 Unprocessable Content' for url 'http://localhost:8001/MCPServer/available_tools?agents=%7B%22agent_1%22%3A+%22character%22%2C+%22agent_2%22%3A+%22database%22%7D&tools=%7B%22tool_1%22%3A+%22check_character_limit%22%2C+%22tool_2%22%3A+%22check_for_active_character%22%2C+%22tool_3%22%3A+%22create_character%22%7D'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/422
2025-07-25 17:32:25,206 - INFO - api_server.py - 24 - api_server: Application shutdown...
2025-07-25 17:32:36,732 - INFO - api_server.py - 19 - api_server: Application startup...
2025-07-25 17:32:40,116 - INFO - api_server.py - 24 - api_server: Application shutdown...
2025-07-25 17:32:49,416 - INFO - api_server.py - 19 - api_server: Application startup...
2025-07-25 17:33:07,335 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-25 17:33:07,844 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents "HTTP/1.1 200 OK"
2025-07-25 17:33:20,389 - ERROR - app.py - 35 - app: Error occurred while getting MCP tools: 
2025-07-25 17:38:45,642 - INFO - api_server.py - 24 - api_server: Application shutdown...
2025-07-25 17:38:57,410 - INFO - api_server.py - 19 - api_server: Application startup...
2025-07-25 17:39:03,857 - INFO - api_server.py - 24 - api_server: Application shutdown...
2025-07-25 17:39:13,458 - INFO - api_server.py - 19 - api_server: Application startup...
2025-07-25 17:39:13,460 - INFO - api_server.py - 24 - api_server: Application shutdown...
2025-07-25 17:39:23,452 - INFO - api_server.py - 19 - api_server: Application startup...
2025-07-25 17:39:33,486 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-25 17:39:35,896 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents "HTTP/1.1 200 OK"
2025-07-25 17:39:48,719 - ERROR - app.py - 35 - app: Error occurred while getting MCP tools: 
2025-07-25 17:43:22,595 - INFO - api_server.py - 24 - api_server: Application shutdown...
2025-07-25 17:43:34,181 - INFO - api_server.py - 19 - api_server: Application startup...
2025-07-25 17:43:44,867 - INFO - api_server.py - 24 - api_server: Application shutdown...
2025-07-25 17:43:54,505 - INFO - api_server.py - 19 - api_server: Application startup...
2025-07-25 17:45:41,777 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-25 17:45:42,390 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents "HTTP/1.1 200 OK"
2025-07-25 17:45:44,473 - ERROR - app.py - 35 - app: Error occurred while getting MCP tools: get_available_tools() missing 1 required positional argument: 'tools'
2025-07-25 17:45:59,277 - INFO - api_server.py - 24 - api_server: Application shutdown...
2025-07-25 17:46:11,210 - INFO - api_server.py - 19 - api_server: Application startup...
2025-07-25 17:46:17,182 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-25 17:46:17,745 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents "HTTP/1.1 200 OK"
2025-07-25 17:46:30,512 - ERROR - app.py - 35 - app: Error occurred while getting MCP tools: 
2025-07-25 17:47:00,783 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-25 17:47:01,224 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents "HTTP/1.1 200 OK"
2025-07-25 17:47:12,903 - ERROR - app.py - 35 - app: Error occurred while getting MCP tools: 
2025-07-25 17:47:30,399 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-25 17:47:30,841 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents "HTTP/1.1 200 OK"
2025-07-25 17:47:42,483 - ERROR - app.py - 35 - app: Error occurred while getting MCP tools: 
2025-07-25 17:50:40,862 - INFO - api_server.py - 24 - api_server: Application shutdown...
2025-07-25 17:50:53,209 - INFO - api_server.py - 19 - api_server: Application startup...
2025-07-25 17:50:53,211 - INFO - api_server.py - 24 - api_server: Application shutdown...
2025-07-25 17:51:02,720 - INFO - api_server.py - 19 - api_server: Application startup...
2025-07-25 17:51:25,044 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-25 17:51:25,640 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents "HTTP/1.1 200 OK"
2025-07-25 17:51:28,083 - INFO - _client.py - 1740 - _client: HTTP Request: POST http://localhost:8001/MCPServer/available_tools "HTTP/1.1 405 Method Not Allowed"
2025-07-25 17:51:28,084 - ERROR - app.py - 35 - app: Error occurred while getting MCP tools: Client error '405 Method Not Allowed' for url 'http://localhost:8001/MCPServer/available_tools'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/405
2025-07-25 17:52:10,637 - INFO - api_server.py - 24 - api_server: Application shutdown...
2025-07-25 17:52:23,047 - INFO - api_server.py - 19 - api_server: Application startup...
2025-07-25 17:52:23,049 - INFO - api_server.py - 24 - api_server: Application shutdown...
2025-07-25 17:52:32,789 - INFO - api_server.py - 19 - api_server: Application startup...
2025-07-25 17:52:32,794 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-25 17:52:33,307 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents "HTTP/1.1 200 OK"
2025-07-25 17:52:46,815 - ERROR - app.py - 35 - app: Error occurred while getting MCP tools: 
2025-07-25 19:39:36,848 - INFO - api_server.py - 19 - api_server: Application startup...
2025-07-25 19:42:52,123 - INFO - api_server.py - 24 - api_server: Application shutdown...
2025-07-25 19:43:01,715 - INFO - api_server.py - 19 - api_server: Application startup...
2025-07-25 19:44:36,897 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-25 19:44:37,507 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents "HTTP/1.1 200 OK"
2025-07-25 19:44:48,173 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents?agents=%7B%27agent_1%27%3A+%27character%27%2C+%27agent_2%27%3A+%27database%27%7D&tools=%7B%27tool_1%27%3A+%27check_character_limit%27%2C+%27tool_2%27%3A+%27check_for_active_character%27%2C+%27tool_3%27%3A+%27create_character%27%7D "HTTP/1.1 200 OK"
2025-07-25 19:44:50,842 - INFO - app.py - 21 - app: Intent determined: create_character
2025-07-25 19:44:50,843 - INFO - app.py - 22 - app: Tasks determined: {'task_1': {'agent': 'character', 'tool': {'name': 'check_character_limit', 'fields': {}}}, 'task_2': {'agent': 'character', 'tool': {'name': 'check_for_active_character', 'fields': {'user_id': '123e4567-e89b-12d3-a456-426614174000'}}}, 'task_3': {'agent': 'database', 'tool': {'name': 'create_character', 'fields': {'user_id': '123e4567-e89b-12d3-a456-426614174000', 'server_id': '123e4567-e89b-12d3-a456-426614174111', 'name': 'leeroy', 'class': 'warrior'}}}}
2025-07-25 19:44:51,648 - INFO - _client.py - 1740 - _client: HTTP Request: POST http://localhost:8001/orchestrator "HTTP/1.1 200 OK"
2025-07-25 19:45:02,080 - ERROR - app.py - 28 - app: Error in MCP workflow: Error importing agent: No module named 'Agents.database'
2025-07-25 19:45:29,479 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-25 19:45:29,915 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents "HTTP/1.1 200 OK"
2025-07-25 19:45:55,928 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents?agents=%7B%27agent_1%27%3A+%27character%27%2C+%27agent_2%27%3A+%27database%27%7D&tools=%7B%27tool_1%27%3A+%27check_character_limit%27%2C+%27tool_2%27%3A+%27check_for_active_character%27%2C+%27tool_3%27%3A+%27create_character%27%7D "HTTP/1.1 200 OK"
2025-07-25 19:45:58,707 - INFO - app.py - 21 - app: Intent determined: create_character
2025-07-25 19:46:48,954 - INFO - app.py - 22 - app: Tasks determined: {'task_1': {'agent': 'character', 'tool': {'name': 'check_character_limit', 'fields': {}}}, 'task_2': {'agent': 'character', 'tool': {'name': 'check_for_active_character', 'fields': {'user_id': '123e4567-e89b-12d3-a456-426614174000'}}}, 'task_3': {'agent': 'database', 'tool': {'name': 'create_character', 'fields': {'user_id': '123e4567-e89b-12d3-a456-426614174000', 'server_id': '123e4567-e89b-12d3-a456-426614174111', 'name': 'leeroy', 'class': 'warrior'}}}}
2025-07-25 19:46:49,406 - INFO - _client.py - 1740 - _client: HTTP Request: POST http://localhost:8001/orchestrator "HTTP/1.1 200 OK"
2025-07-25 19:47:20,300 - ERROR - app.py - 28 - app: Error in MCP workflow: Error importing agent: No module named 'Agents.database'
2025-07-25 19:47:24,149 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-25 19:47:24,591 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents "HTTP/1.1 200 OK"
2025-07-25 19:47:26,242 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents?agents=%7B%27agent_1%27%3A+%27character%27%2C+%27agent_2%27%3A+%27database%27%7D&tools=%7B%27tool_1%27%3A+%27check_character_limit%27%2C+%27tool_2%27%3A+%27check_for_active_character%27%2C+%27tool_3%27%3A+%27create_character%27%7D "HTTP/1.1 200 OK"
2025-07-25 19:47:50,244 - INFO - app.py - 21 - app: Intent determined: create_character
2025-07-25 19:47:50,245 - INFO - app.py - 22 - app: Tasks determined: {'task_1': {'agent': 'character', 'tool': {'name': 'check_character_limit', 'fields': {}}}, 'task_2': {'agent': 'character', 'tool': {'name': 'check_for_active_character', 'fields': {'user_id': '123e4567-e89b-12d3-a456-426614174000'}}}, 'task_3': {'agent': 'database', 'tool': {'name': 'create_character', 'fields': {'user_id': '123e4567-e89b-12d3-a456-426614174000', 'server_id': '123e4567-e89b-12d3-a456-426614174111', 'name': 'leeroy', 'class': 'warrior'}}}}
2025-07-25 19:47:50,994 - INFO - _client.py - 1740 - _client: HTTP Request: POST http://localhost:8001/orchestrator "HTTP/1.1 200 OK"
2025-07-25 19:47:54,154 - ERROR - app.py - 28 - app: Error in MCP workflow: Error importing agent: No module named 'Agents.database'
2025-07-25 19:47:56,424 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-25 19:47:56,854 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents "HTTP/1.1 200 OK"
2025-07-25 19:48:09,687 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents?agents=%7B%27agent_1%27%3A+%27character%27%2C+%27agent_2%27%3A+%27database%27%7D&tools=%7B%27tool_1%27%3A+%27check_character_limit%27%2C+%27tool_2%27%3A+%27check_for_active_character%27%2C+%27tool_3%27%3A+%27create_character%27%7D "HTTP/1.1 200 OK"
2025-07-25 19:49:16,942 - INFO - app.py - 21 - app: Intent determined: create_character
2025-07-25 19:49:16,942 - INFO - app.py - 22 - app: Tasks determined: {'task_1': {'agent': 'character', 'tool': {'name': 'check_character_limit', 'fields': {}}}, 'task_2': {'agent': 'character', 'tool': {'name': 'check_for_active_character', 'fields': {'user_id': '123e4567-e89b-12d3-a456-426614174000'}}}, 'task_3': {'agent': 'database', 'tool': {'name': 'create_character', 'fields': {'user_id': '123e4567-e89b-12d3-a456-426614174000', 'server_id': '123e4567-e89b-12d3-a456-426614174111', 'name': 'leeroy', 'class': 'warrior'}}}}
2025-07-25 19:49:17,397 - INFO - _client.py - 1740 - _client: HTTP Request: POST http://localhost:8001/orchestrator "HTTP/1.1 200 OK"
2025-07-25 19:49:20,274 - ERROR - app.py - 28 - app: Error in MCP workflow: Error importing agent: No module named 'Agents.database'
2025-07-25 19:50:18,903 - INFO - api_server.py - 24 - api_server: Application shutdown...
2025-07-25 19:50:30,831 - INFO - api_server.py - 19 - api_server: Application startup...
2025-07-25 19:50:31,271 - INFO - api_server.py - 24 - api_server: Application shutdown...
2025-07-25 19:50:40,723 - INFO - api_server.py - 19 - api_server: Application startup...
2025-07-25 19:50:50,041 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-25 19:50:50,576 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents "HTTP/1.1 200 OK"
2025-07-25 19:50:55,005 - INFO - _client.py - 1740 - _client: HTTP Request: POST http://localhost:8001/MCPServer/available_intents "HTTP/1.1 405 Method Not Allowed"
2025-07-25 19:50:55,007 - ERROR - app.py - 35 - app: Error occurred while getting MCP tools: Client error '405 Method Not Allowed' for url 'http://localhost:8001/MCPServer/available_intents'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/405
2025-07-25 19:51:50,516 - INFO - api_server.py - 24 - api_server: Application shutdown...
2025-07-25 19:52:02,201 - INFO - api_server.py - 19 - api_server: Application startup...
2025-07-25 19:52:03,707 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-25 19:52:04,224 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents "HTTP/1.1 200 OK"
2025-07-25 19:52:08,136 - INFO - _client.py - 1740 - _client: HTTP Request: POST http://localhost:8001/MCPServer/available_intents "HTTP/1.1 405 Method Not Allowed"
2025-07-25 19:53:24,235 - ERROR - app.py - 35 - app: Error occurred while getting MCP tools: Client error '405 Method Not Allowed' for url 'http://localhost:8001/MCPServer/available_intents'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/405
2025-07-25 19:53:24,343 - INFO - api_server.py - 24 - api_server: Application shutdown...
2025-07-25 19:53:42,384 - INFO - api_server.py - 19 - api_server: Application startup...
2025-07-25 19:54:56,306 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-25 19:54:56,877 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents "HTTP/1.1 200 OK"
2025-07-25 19:55:09,053 - ERROR - app.py - 35 - app: Error occurred while getting MCP tools: 
2025-07-25 20:09:36,814 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-25 20:09:37,318 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents "HTTP/1.1 200 OK"
2025-07-25 20:09:49,321 - ERROR - app.py - 35 - app: Error occurred while getting MCP tools: 
2025-07-25 20:16:50,076 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-25 20:16:50,579 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents "HTTP/1.1 200 OK"
2025-07-25 20:17:02,410 - ERROR - app.py - 35 - app: Error occurred while getting MCP tools: 
2025-07-25 20:31:45,422 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-25 20:31:45,867 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents "HTTP/1.1 200 OK"
2025-07-25 20:31:57,615 - ERROR - app.py - 35 - app: Error occurred while getting MCP tools: 
2025-07-25 20:51:57,008 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-25 20:51:57,436 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents "HTTP/1.1 200 OK"
2025-07-25 20:52:09,201 - ERROR - app.py - 35 - app: Error occurred while getting MCP tools: 
2025-07-26 09:56:31,198 - INFO - api_server.py - 19 - api_server: Application startup...
2025-07-26 09:57:14,289 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-26 09:57:14,789 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents "HTTP/1.1 200 OK"
2025-07-26 09:57:26,532 - ERROR - app.py - 35 - app: Error occurred while getting MCP tools: 
2025-07-26 09:57:32,722 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-26 09:57:33,145 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents "HTTP/1.1 200 OK"
2025-07-26 09:57:34,658 - INFO - _client.py - 1740 - _client: HTTP Request: POST http://localhost:8001/MCPServer/available_tools "HTTP/1.1 200 OK"
2025-07-26 09:59:49,986 - ERROR - llm_service.py - 94 - llm_service: An unexpected error occurred in handle_LLM_intent: replace() argument 2 must be str, not builtin_function_or_method
2025-07-26 09:59:49,987 - INFO - app.py - 21 - app: Intent determined: None
2025-07-26 09:59:49,988 - INFO - app.py - 22 - app: Tasks determined: None
2025-07-26 09:59:50,430 - INFO - _client.py - 1740 - _client: HTTP Request: POST http://localhost:8001/orchestrator "HTTP/1.1 500 Internal Server Error"
2025-07-26 09:59:50,432 - ERROR - app.py - 35 - app: Error occurred while getting MCP tools: Server error '500 Internal Server Error' for url 'http://localhost:8001/orchestrator'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500
2025-07-26 09:59:54,864 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-26 09:59:55,293 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents "HTTP/1.1 200 OK"
2025-07-26 10:00:06,813 - ERROR - app.py - 35 - app: Error occurred while getting MCP tools: 
2025-07-26 10:05:14,788 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-26 10:05:15,216 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents "HTTP/1.1 200 OK"
2025-07-26 10:05:16,654 - INFO - _client.py - 1740 - _client: HTTP Request: POST http://localhost:8001/MCPServer/available_tools "HTTP/1.1 200 OK"
2025-07-26 10:35:53,040 - ERROR - llm_service.py - 94 - llm_service: An unexpected error occurred in handle_LLM_intent: replace() argument 2 must be str, not builtin_function_or_method
2025-07-26 10:35:53,041 - INFO - app.py - 21 - app: Intent determined: None
2025-07-26 10:35:53,041 - INFO - app.py - 22 - app: Tasks determined: None
2025-07-26 10:35:53,480 - INFO - _client.py - 1740 - _client: HTTP Request: POST http://localhost:8001/orchestrator "HTTP/1.1 500 Internal Server Error"
2025-07-26 10:35:53,481 - ERROR - app.py - 35 - app: Error occurred while getting MCP tools: Server error '500 Internal Server Error' for url 'http://localhost:8001/orchestrator'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500
2025-07-26 10:36:11,084 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-26 10:36:11,522 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents "HTTP/1.1 200 OK"
2025-07-26 10:36:17,136 - INFO - _client.py - 1740 - _client: HTTP Request: POST http://localhost:8001/MCPServer/available_tools "HTTP/1.1 200 OK"
2025-07-26 10:37:08,582 - ERROR - llm_service.py - 94 - llm_service: An unexpected error occurred in handle_LLM_intent: replace() argument 2 must be str, not builtin_function_or_method
2025-07-26 10:37:08,586 - INFO - app.py - 21 - app: Intent determined: None
2025-07-26 10:37:08,587 - INFO - app.py - 22 - app: Tasks determined: None
2025-07-26 10:37:09,011 - INFO - _client.py - 1740 - _client: HTTP Request: POST http://localhost:8001/orchestrator "HTTP/1.1 500 Internal Server Error"
2025-07-26 10:37:09,013 - ERROR - app.py - 35 - app: Error occurred while getting MCP tools: Server error '500 Internal Server Error' for url 'http://localhost:8001/orchestrator'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500
2025-07-26 10:37:21,690 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-26 10:37:22,135 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents "HTTP/1.1 200 OK"
2025-07-26 10:37:25,593 - INFO - _client.py - 1740 - _client: HTTP Request: POST http://localhost:8001/MCPServer/available_tools "HTTP/1.1 200 OK"
2025-07-26 10:55:07,735 - ERROR - llm_service.py - 94 - llm_service: An unexpected error occurred in handle_LLM_intent: replace() argument 2 must be str, not builtin_function_or_method
2025-07-26 10:55:07,737 - INFO - app.py - 21 - app: Intent determined: None
2025-07-26 10:55:07,737 - INFO - app.py - 22 - app: Tasks determined: None
2025-07-26 10:55:09,555 - INFO - _client.py - 1740 - _client: HTTP Request: POST http://localhost:8001/orchestrator "HTTP/1.1 500 Internal Server Error"
2025-07-26 10:55:09,557 - ERROR - app.py - 35 - app: Error occurred while getting MCP tools: Server error '500 Internal Server Error' for url 'http://localhost:8001/orchestrator'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500
2025-07-26 10:55:09,664 - INFO - api_server.py - 24 - api_server: Application shutdown...
2025-07-26 10:55:20,717 - INFO - api_server.py - 19 - api_server: Application startup...
2025-07-26 10:56:25,203 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-26 10:56:25,785 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents "HTTP/1.1 200 OK"
2025-07-26 10:56:31,311 - INFO - _client.py - 1740 - _client: HTTP Request: POST http://localhost:8001/MCPServer/available_tools "HTTP/1.1 200 OK"
2025-07-26 10:57:31,351 - INFO - app.py - 21 - app: Intent determined: create_character
2025-07-26 10:57:31,352 - INFO - app.py - 22 - app: Tasks determined: {'task_1': {'agent': 'character', 'tool': {'name': 'check_character_limit', 'fields': {'server_id': '123e4567-e89b-12d3-a456-426614174111', 'user_id': '123e4567-e89b-12d3-a456-426614174000'}}}, 'task_2': {'agent': 'character', 'tool': {'name': 'check_for_active_character', 'fields': {'server_id': '123e4567-e89b-12d3-a456-426614174111', 'user_id': '123e4567-e89b-12d3-a456-426614174000'}}}, 'task_3': {'agent': 'character', 'tool': {'name': 'create_character', 'fields': {'first_name': None, 'last_name': None, 'characters_name': 'leeroy', 'characters_class': 'warrior', 'user_id': '123e4567-e89b-12d3-a456-426614174000', 'server_id': '123e4567-e89b-12d3-a456-426614174111'}}}}
2025-07-26 10:57:32,147 - INFO - _client.py - 1740 - _client: HTTP Request: POST http://localhost:8001/orchestrator "HTTP/1.1 200 OK"
2025-07-26 10:57:32,148 - ERROR - app.py - 35 - app: Error occurred while getting MCP tools: name 'handle_LLM_tools' is not defined
2025-07-26 10:57:32,177 - INFO - api_server.py - 24 - api_server: Application shutdown...
2025-07-26 10:57:43,194 - INFO - api_server.py - 19 - api_server: Application startup...
2025-07-26 10:57:45,353 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-26 10:57:45,858 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents "HTTP/1.1 200 OK"
2025-07-26 10:57:52,327 - INFO - _client.py - 1740 - _client: HTTP Request: POST http://localhost:8001/MCPServer/available_tools "HTTP/1.1 200 OK"
2025-07-26 10:58:33,826 - INFO - app.py - 21 - app: Intent determined: create_character
2025-07-26 10:58:33,827 - INFO - app.py - 22 - app: Tasks determined: {'task_1': {'agent': 'agent_1', 'tool': {'name': 'check_character_limit', 'fields': {'server_id': '123e4567-e89b-12d3-a456-426614174111', 'user_id': '123e4567-e89b-12d3-a456-426614174000'}}}, 'task_2': {'agent': 'agent_1', 'tool': {'name': 'check_for_active_character', 'fields': {'server_id': '123e4567-e89b-12d3-a456-426614174111', 'user_id': '123e4567-e89b-12d3-a456-426614174000'}}}, 'task_3': {'agent': 'agent_1', 'tool': {'name': 'create_character', 'fields': {'first_name': None, 'last_name': None, 'characters_name': 'leeroy', 'characters_class': 'warrior', 'user_id': '123e4567-e89b-12d3-a456-426614174000', 'server_id': '123e4567-e89b-12d3-a456-426614174111'}}}}
2025-07-26 10:58:34,270 - INFO - _client.py - 1740 - _client: HTTP Request: POST http://localhost:8001/orchestrator "HTTP/1.1 200 OK"
2025-07-26 10:58:34,272 - ERROR - app.py - 28 - app: Error in MCP workflow: Error importing agent: No module named 'Agents.agent_1'
2025-07-26 10:58:50,148 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-26 10:58:50,574 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents "HTTP/1.1 200 OK"
2025-07-26 10:58:55,130 - INFO - _client.py - 1740 - _client: HTTP Request: POST http://localhost:8001/MCPServer/available_tools "HTTP/1.1 200 OK"
2025-07-26 11:00:28,895 - INFO - app.py - 21 - app: Intent determined: create_character
2025-07-26 11:00:28,897 - INFO - app.py - 22 - app: Tasks determined: {'task_1': {'agent': 'agent_1', 'tool': {'name': 'check_character_limit', 'fields': {'server_id': '123e4567-e89b-12d3-a456-426614174111', 'user_id': '123e4567-e89b-12d3-a456-426614174000'}}}, 'task_2': {'agent': 'agent_1', 'tool': {'name': 'check_for_active_character', 'fields': {'server_id': '123e4567-e89b-12d3-a456-426614174111', 'user_id': '123e4567-e89b-12d3-a456-426614174000'}}}, 'task_3': {'agent': 'agent_1', 'tool': {'name': 'create_character', 'fields': {'first_name': None, 'last_name': None, 'characters_name': 'leeroy', 'characters_class': 'warrior', 'user_id': '123e4567-e89b-12d3-a456-426614174000', 'server_id': '123e4567-e89b-12d3-a456-426614174111'}}}}
2025-07-26 11:00:29,339 - INFO - _client.py - 1740 - _client: HTTP Request: POST http://localhost:8001/orchestrator "HTTP/1.1 200 OK"
2025-07-26 11:00:29,340 - ERROR - app.py - 28 - app: Error in MCP workflow: Error importing agent: No module named 'Agents.agent_1'
2025-07-26 11:00:32,444 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-26 11:00:32,870 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents "HTTP/1.1 200 OK"
2025-07-26 11:00:40,208 - INFO - _client.py - 1740 - _client: HTTP Request: POST http://localhost:8001/MCPServer/available_tools "HTTP/1.1 200 OK"
2025-07-26 11:06:41,392 - INFO - app.py - 21 - app: Intent determined: create_character
2025-07-26 11:06:41,394 - INFO - app.py - 22 - app: Tasks determined: {'task_1': {'agent': 'character', 'tool': {'name': 'check_character_limit', 'fields': {'server_id': '123e4567-e89b-12d3-a456-426614174111', 'user_id': '123e4567-e89b-12d3-a456-426614174000'}}}, 'task_2': {'agent': 'character', 'tool': {'name': 'check_for_active_character', 'fields': {'server_id': '123e4567-e89b-12d3-a456-426614174111', 'user_id': '123e4567-e89b-12d3-a456-426614174000'}}}, 'task_3': {'agent': 'character', 'tool': {'name': 'create_character', 'fields': {'first_name': None, 'last_name': None, 'characters_name': 'leeroy', 'characters_class': 'warrior', 'user_id': '123e4567-e89b-12d3-a456-426614174000', 'server_id': '123e4567-e89b-12d3-a456-426614174111'}}}}
2025-07-26 11:13:10,234 - INFO - _client.py - 1740 - _client: HTTP Request: POST http://localhost:8001/orchestrator "HTTP/1.1 200 OK"
2025-07-26 11:13:10,236 - ERROR - app.py - 35 - app: Error occurred while getting MCP tools: name 'handle_LLM_tools' is not defined
2025-07-26 11:23:29,442 - INFO - api_server.py - 24 - api_server: Application shutdown...
2025-07-26 11:23:40,592 - INFO - api_server.py - 19 - api_server: Application startup...
2025-07-26 11:23:58,067 - INFO - api_server.py - 24 - api_server: Application shutdown...
2025-07-26 11:24:06,993 - INFO - api_server.py - 19 - api_server: Application startup...
2025-07-26 11:24:29,856 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-26 11:24:30,347 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents "HTTP/1.1 200 OK"
2025-07-26 11:24:42,284 - INFO - _client.py - 1740 - _client: HTTP Request: POST http://localhost:8001/MCPServer/available_tools "HTTP/1.1 200 OK"
2025-07-26 11:24:45,974 - INFO - app.py - 21 - app: Intent determined: create_character
2025-07-26 11:24:45,974 - INFO - app.py - 22 - app: Tasks determined: {'task_1': {'agent': 'agent_1', 'tool': {'name': 'check_character_limit', 'fields': {'server_id': '123e4567-e89b-12d3-a456-426614174111', 'user_id': '123e4567-e89b-12d3-a456-426614174000'}}}, 'task_2': {'agent': 'agent_1', 'tool': {'name': 'check_for_active_character', 'fields': {'server_id': '123e4567-e89b-12d3-a456-426614174111', 'user_id': '123e4567-e89b-12d3-a456-426614174000'}}}, 'task_3': {'agent': 'agent_1', 'tool': {'name': 'create_character', 'fields': {'first_name': None, 'last_name': None, 'characters_name': 'leeroy', 'characters_class': 'warrior', 'user_id': '123e4567-e89b-12d3-a456-426614174000', 'server_id': '123e4567-e89b-12d3-a456-426614174111'}}}}
2025-07-26 11:25:01,321 - INFO - _client.py - 1740 - _client: HTTP Request: POST http://localhost:8001/orchestrator "HTTP/1.1 200 OK"
2025-07-26 11:25:01,323 - ERROR - app.py - 28 - app: Error in MCP workflow: Error importing agent: No module named 'Agents.agent_1'
2025-07-26 11:25:24,365 - INFO - app.py - 14 - app: Executing request with MCP workflow...
2025-07-26 11:25:24,793 - INFO - _client.py - 1740 - _client: HTTP Request: GET http://localhost:8001/MCPServer/available_intents "HTTP/1.1 200 OK"
2025-07-26 11:25:26,299 - INFO - _client.py - 1740 - _client: HTTP Request: POST http://localhost:8001/MCPServer/available_tools "HTTP/1.1 200 OK"
2025-07-26 11:25:29,954 - INFO - app.py - 21 - app: Intent determined: create_character
2025-07-26 11:25:29,954 - INFO - app.py - 22 - app: Tasks determined: {'task_1': {'agent': 'agent_1', 'tool': {'name': 'check_character_limit', 'fields': {'server_id': '123e4567-e89b-12d3-a456-426614174111', 'user_id': '123e4567-e89b-12d3-a456-426614174000'}}}, 'task_2': {'agent': 'agent_1', 'tool': {'name': 'check_for_active_character', 'fields': {'server_id': '123e4567-e89b-12d3-a456-426614174111', 'user_id': '123e4567-e89b-12d3-a456-426614174000'}}}, 'task_3': {'agent': 'agent_1', 'tool': {'name': 'create_character', 'fields': {'first_name': None, 'last_name': None, 'characters_name': 'leeroy', 'characters_class': 'warrior', 'user_id': '123e4567-e89b-12d3-a456-426614174000', 'server_id': '123e4567-e89b-12d3-a456-426614174111'}}}}
2025-07-26 11:25:30,472 - INFO - _client.py - 1740 - _client: HTTP Request: POST http://localhost:8001/orchestrator "HTTP/1.1 200 OK"
2025-07-26 11:25:30,473 - ERROR - app.py - 28 - app: Error in MCP workflow: Error importing agent: No module named 'Agents.agent_1'
2025-07-26 11:27:02,892 - INFO - api_server.py - 24 - api_server: Application shutdown...
